In [7]:
faqs = """Q 1. What is the reason for these Cyber Security Directions?
Ans: The Internet in India is growing fast and over the next few years over 120 Crore
Indians will have access to the Internet and use it for business, education, finance and
myriad other applications and services including Digital Government services. The
Internet has seen growth in innovation and at the same time it has seen rise in crimes,
user harm and other challenges to online safety. It is the Government of India’s policy
goal to ensure that Indian Internet users experience a Safe & Trusted Internet. Cyber
Security Directions are a part of the overall framework of ensuring online safety and
trust for users.
Q 2. What is CERT-In and what is the status of CERT-In?
Ans.: ‘Indian Computer Emergency Response Team’ (CERT-In) is the national agency
for cyber security incident response and proactive measures for prevention of cyber
incidents in the Country. CERT-In has been appointed by Central Government vide
notification dated 27th October 2009 in terms of the provisions of section 70B (1) of The
Information Technology Act, 2000 (IT Act, 2000).
Q 3. What is Cyber Security Incident?
Ans.: “Cyber Security Incident” means any real or suspected adverse event in relation
to cyber security that violates an explicitly or implicitly applicable security policy
resulting in unauthorised access, denial of service or disruption, unauthorised use of a
computer resource for processing or storage of information or changes in data,
information without authorisation.
Q 4. Why Cyber Security is important?
Ans.: The digital technology and usage of internet has grown exponentially and is
integral part of modern life. Today, cyberspace is the common platform used by citizens,
businesses and Governments for communication, dissemination of information,
e-commerce, services, economic activities, education, entertainment etc. At the same
time, the advancement of technology has opened vulnerabilities for exploitation by the
malicious actors. Cyber security is the protection of electronic data and information. To
deal with the emerging cyber threat landscape and to ensure safe usage of digital
technologies by users, the legal, technical, organizational and collaborative measures
need to be taken by stakeholders.
Q 5. What process was followed to arrive at the Cyber Security Directions of
28.04.2022?
Ans.: CERT-In is in operation since the year 2004. Based on analysis of cyber security
incidents and trends certain gaps in processes of organisations and service providers
have been observed by CERT-In. Accordingly, consultations with the industry and
Government organisations have been held from time to time and based upon the inputs
received from the stakeholders, draft directions were framed. Subsequently, CERT-In
under the aegis of MeitY held stakeholder consultation in March 2022 towards
finalisation of the directions.
Q 6. What are the functions of CERT-In in the area of cyber security?
Ans.: CERT-In performs the statutory functions in the area of Cyber Security as
specified in sub-section (4) of section 70B of the Information Technology Act, 2000,
which enshrines that CERT-In shall serve as the national agency for performing the
following functions in the area of cyber security :-
a) collection, analysis and dissemination of information on cyber incidents;
b) forecast and alerts of cyber security incidents;
c) emergency measures for handling cyber security incidents;
d) coordination of cyber incident response activities;
e) issue guidelines, advisories, vulnerability notes and whitepapers relating to
information security practices, procedures, prevention, response and reporting of
cyber incidents;
f) such other functions relating to cyber security as may be prescribed.
Q 7. Who do these Cyber Security Directions of 28.04.2022 apply to?
Ans.: Service providers, intermediaries, data centres, body corporate, Virtual Private
Server (VPS) providers, Cloud service providers , VPN Service providers, virtual asset
service providers, virtual asset exchange providers, custodian wallet providers and
Government organisations shall follow these Cyber Security Directions of 28.4.2022 as
applicable to them. Individual citizens are not covered by these Directions.
Q 10. The Information Technology (Intermediary Guidelines and Digital Media
Ethics Code) Rules, 2021 provide that “The intermediary shall report cyber security
incidents and also share cyber security incidents related information with the Indian
Computer Emergency Response Team”. Do intermediaries have to mandatorily
report any and all cyber security incidents or only those specified in the Annexure
to the Rules?
Ans.: It is correct that the intermediaries as defined under the Information Technology
Act and Rules made thereunder to report cyber security incidents and share any related
information thereof with CERT-In. The Rule 3(1) (l) of the Information Technology
(Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021 provides that
“The intermediary shall report cyber security incidents and share related information
with the Indian Computer Emergency Response Team in accordance with the policies
and procedures as mentioned in the Information Technology (The Indian Computer
Emergency Response Team and Manner of Performing Functions and Duties) Rules,
2013”. In this context, it is obligatory to note that in terms of Rule 12 of the CERT-In
Rules 2013, the type of cyber security incidents as identified in the Annexure [of the
Rules] and also brought out in the Cyber Security Directions of 28.04.2022, are to be
mandatorily reported to CERT-In by any organization or corporate entity, including
intermediaries affected by cyber security incidents as early as possible to leave scope for
action.
"""

In [8]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [9]:
tokenizer = Tokenizer()

In [10]:
tokenizer.fit_on_texts([faqs])

In [11]:
tokenizer.word_index

{'the': 1,
 'of': 2,
 'in': 3,
 'and': 4,
 'cyber': 5,
 'security': 6,
 'to': 7,
 'information': 8,
 'is': 9,
 'cert': 10,
 'incidents': 11,
 'for': 12,
 'directions': 13,
 'by': 14,
 'as': 15,
 'q': 16,
 'ans': 17,
 'technology': 18,
 'providers': 19,
 'that': 20,
 'response': 21,
 'or': 22,
 'rules': 23,
 'what': 24,
 'internet': 25,
 'it': 26,
 'service': 27,
 'with': 28,
 'digital': 29,
 'government': 30,
 'has': 31,
 'computer': 32,
 'emergency': 33,
 '2022': 34,
 'functions': 35,
 'these': 36,
 'have': 37,
 'time': 38,
 'indian': 39,
 'a': 40,
 'are': 41,
 'act': 42,
 'any': 43,
 '28': 44,
 'shall': 45,
 'intermediaries': 46,
 'intermediary': 47,
 'report': 48,
 '1': 49,
 'other': 50,
 'services': 51,
 'at': 52,
 'users': 53,
 'incident': 54,
 'measures': 55,
 'been': 56,
 'section': 57,
 '2000': 58,
 'data': 59,
 '4': 60,
 'be': 61,
 '04': 62,
 'organisations': 63,
 'area': 64,
 'guidelines': 65,
 'virtual': 66,
 'share': 67,
 'related': 68,
 'over': 69,
 'access': 70,
 'use': 7

In [12]:
from keras.utils import pad_sequences

In [19]:
# generating the input data

input_sequences = []

for sentence in faqs.split('\n'):
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1, len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])

In [20]:
input_sequences

[[16, 49],
 [16, 49, 24],
 [16, 49, 24, 9],
 [16, 49, 24, 9, 1],
 [16, 49, 24, 9, 1, 119],
 [16, 49, 24, 9, 1, 119, 12],
 [16, 49, 24, 9, 1, 119, 12, 36],
 [16, 49, 24, 9, 1, 119, 12, 36, 5],
 [16, 49, 24, 9, 1, 119, 12, 36, 5, 6],
 [16, 49, 24, 9, 1, 119, 12, 36, 5, 6, 13],
 [17, 1],
 [17, 1, 25],
 [17, 1, 25, 3],
 [17, 1, 25, 3, 120],
 [17, 1, 25, 3, 120, 9],
 [17, 1, 25, 3, 120, 9, 121],
 [17, 1, 25, 3, 120, 9, 121, 122],
 [17, 1, 25, 3, 120, 9, 121, 122, 4],
 [17, 1, 25, 3, 120, 9, 121, 122, 4, 69],
 [17, 1, 25, 3, 120, 9, 121, 122, 4, 69, 1],
 [17, 1, 25, 3, 120, 9, 121, 122, 4, 69, 1, 123],
 [17, 1, 25, 3, 120, 9, 121, 122, 4, 69, 1, 123, 124],
 [17, 1, 25, 3, 120, 9, 121, 122, 4, 69, 1, 123, 124, 125],
 [17, 1, 25, 3, 120, 9, 121, 122, 4, 69, 1, 123, 124, 125, 69],
 [17, 1, 25, 3, 120, 9, 121, 122, 4, 69, 1, 123, 124, 125, 69, 126],
 [17, 1, 25, 3, 120, 9, 121, 122, 4, 69, 1, 123, 124, 125, 69, 126, 127],
 [128, 129],
 [128, 129, 37],
 [128, 129, 37, 70],
 [128, 129, 37, 70, 7],

In [24]:
# which is the longest sentence ? (needed for padding)

max_len = max([len(x) for x in input_sequences])  # 19

In [30]:
# Padding

from tensorflow.keras.preprocessing.sequence import pad_sequences

padded_input_sequences = pad_sequences(input_sequences, maxlen=max_len, padding='pre')

In [31]:
print(padded_input_sequences)

[[  0   0   0 ...   0  16  49]
 [  0   0   0 ...  16  49  24]
 [  0   0   0 ...  49  24   9]
 ...
 [  0   0   0 ... 333   7 334]
 [  0   0   0 ...   7 334 335]
 [  0   0   0 ... 334 335  12]]


In [33]:
# all except the last character

x = padded_input_sequences[:, :-1]

In [34]:
# the last characters

y = padded_input_sequences[:,-1]

In [35]:
y

array([ 49,  24,   9,   1, 119,  12,  36,   5,   6,  13,   1,  25,   3,
       120,   9, 121, 122,   4,  69,   1, 123, 124, 125,  69, 126, 127,
       129,  37,  70,   7,   1,  25,   4,  71,  26,  12, 130,  72, 131,
         4,  50, 133,   4,  51,  73,  29,  30,  51,   1,  31,  74, 134,
         3, 135,   4,  52,   1,  75,  38,  26,  31,  74, 136,   3, 137,
       139,   4,  50, 140,   7,  76,  77,  26,   9,   1,  30,   2, 141,
        78,   7,  79,  20,  39,  25,  53, 143,  40,  80, 144,  25,   5,
        13,  41,  40,  81,   2,   1, 145, 146,   2, 147,  76,  77,   4,
        12,  53, 149,  24,   9,  10,   3,   4,  24,   9,   1, 150,   2,
        10,   3, 151,  32,  33,  21, 152,  10,   3,   9,   1,  82,  83,
         5,   6,  54,  21,   4, 153,  55,  12,  84,   2,   5,   3,   1,
       154,  10,   3,  31,  56, 155,  14, 156,  30, 157, 159, 160, 161,
       162,   3,  85,   2,   1, 163,   2,  57,  86,  49,   2,   1,  18,
        42,  58,  26,  42,  58,  87,  24,   9,   5,   6,  54, 16

> This will be a Multi-Class Classification problem

In [36]:
x.shape

(811, 18)

In [37]:
y.shape

(811,)

In [40]:
len(tokenizer.word_index)

336

In [43]:
from tensorflow.keras.utils import to_categorical

y = to_categorical(y, num_classes=337)    # added 1 to the # of words because OneHot Encoding starts with zero but tokenization starts from 1

In [44]:
y.shape

(811, 337)

In [47]:
from tensorflow.keras.layers import Dense,Embedding,LSTM
from tensorflow.keras.models import Sequential

In [50]:
# Architecture: Embedding -> LSTM -> Dense

model = Sequential()

model.add(Embedding(337, 100, input_shape=(19, )))
model.add(LSTM(150))
model.add(Dense(337, activation='softmax'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [51]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 19, 100)        │        33,700 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 150)            │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 337)            │        50,887 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 235,187 (918.70 KB)

 Trainable params: 235,187 (918.70 KB)

 Non-trainable params: 0 (0.00 B)

In [52]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [53]:
history = model.fit(x, y, epochs=100)

Epoch 1/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.0361 - loss: 5.7328
Epoch 2/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0574 - loss: 5.1201
Epoch 3/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0709 - loss: 4.9648
Epoch 4/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0606 - loss: 4.9845
Epoch 5/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0754 - loss: 4.8997
Epoch 6/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1187 - loss: 4.8570
Epoch 7/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1303 - loss: 4.7198
Epoch 8/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1571 - loss: 4.6178
Epoch 9/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1830 - loss: 4.4404
Epoch 10/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1799 - loss: 4.2851
Epoch 11/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2173 - loss: 4.0171
Epoch 12/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy:

In [62]:
import numpy as np

In [69]:
import time

text="The internet"

for i in range(10):

  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]

  # Padding
  padded_token_text = pad_sequences([token_text], maxlen=19, padding='pre')

  # Predict
  pos = np.argmax(model.predict(padded_token_text))    # 11th word is the predicted word

  for word, index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
The internet in
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
The internet in and
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
The internet in and digital
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
The internet in and digital media
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
The internet in and digital media intermediary
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
The internet in and digital media intermediary guidelines
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
The internet in and digital media intermediary guidelines and
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
The internet in and digital media intermediary guidelines and services
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
The internet in and digital media intermediary guidelines and services the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
The internet in and digital media intermediary guidelines and services the government


In [58]:
padded_token_text

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5]],
      dtype=int32)